---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devoxx2023-${TARGET_ROLE}
  namespace: pools
  labels:
    app: devoxx2023
    team: pools
    version: ${VERSION}
    role: ${TARGET_ROLE}
spec:
  replicas: 2
  progressDeadlineSeconds: 240
  selector:
    matchLabels:
      app: devoxx2023
      role: ${TARGET_ROLE}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: devoxx2023
        role: ${TARGET_ROLE}
    spec:
      containers:
      - name: main
        image: 9412036/devoxx2023:${VERSION}
        env:
            - name: Role
              value: ${TARGET_ROLE}
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
